### ISSUE TITLE
Exposing AEAD?

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/ruby-rnp#13]
AEAD is accessible via the command line but doesn't seem allowed here.

**Comment by dewyatt** [comment]
I think I can get this added since https://github.com/riboseinc/rnp/commit/8d0eccd32ea25f6a1183226d0cd113a3a1b78596.

**Comment by dewyatt** [comment]
Revisiting this, it's easy to add but I can't add any useful tests until I have a way to verify AEAD is used (via https://github.com/riboseinc/rnp/issues/668 or otherwise).

When I tested this out today, I made a small mistake and that caused everything to work perfectly except it wasn't actually using AEAD at all. So I would rather wait on this until we have a way to write useful tests.

**Comment by ni4** [comment]
@dewyatt I started some work on JSON packet dumping and adding it to FFI. It is needed for migration of rnp CLI to FFI. `rnp_key_get_someting` functions not always usable since return strings, while rnpkeys require some raw data to print, like algo numbers and so on.

**Comment by dewyatt** [comment]
Thanks to @ni4 this was taken care of in 5b92098.
